all: True
dir: "mocks/"
outpkg: "mocks"
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
with-expecter: True
packages:
  github.com/johnfercher/medium-api/pkg:
    config:
      recursive: True
  github.com/johnfercher/medium-api/internal:
    config:
      recursive: True