// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// APIResponse is an autogenerated mock type for the APIResponse type
type APIResponse struct {
	mock.Mock
}

type APIResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *APIResponse) EXPECT() *APIResponse_Expecter {
	return &APIResponse_Expecter{mock: &_m.Mock}
}

// Code provides a mock function with given fields:
func (_m *APIResponse) Code() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Code")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// APIResponse_Code_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Code'
type APIResponse_Code_Call struct {
	*mock.Call
}

// Code is a helper method to define mock.On call
func (_e *APIResponse_Expecter) Code() *APIResponse_Code_Call {
	return &APIResponse_Code_Call{Call: _e.mock.On("Code")}
}

func (_c *APIResponse_Code_Call) Run(run func()) *APIResponse_Code_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *APIResponse_Code_Call) Return(_a0 int) *APIResponse_Code_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *APIResponse_Code_Call) RunAndReturn(run func() int) *APIResponse_Code_Call {
	_c.Call.Return(run)
	return _c
}

// Object provides a mock function with given fields:
func (_m *APIResponse) Object() interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Object")
	}

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}

// APIResponse_Object_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Object'
type APIResponse_Object_Call struct {
	*mock.Call
}

// Object is a helper method to define mock.On call
func (_e *APIResponse_Expecter) Object() *APIResponse_Object_Call {
	return &APIResponse_Object_Call{Call: _e.mock.On("Object")}
}

func (_c *APIResponse_Object_Call) Run(run func()) *APIResponse_Object_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *APIResponse_Object_Call) Return(_a0 interface{}) *APIResponse_Object_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *APIResponse_Object_Call) RunAndReturn(run func() interface{}) *APIResponse_Object_Call {
	_c.Call.Return(run)
	return _c
}

// NewAPIResponse creates a new instance of APIResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIResponse(t interface {
	mock.TestingT
	Cleanup(func())
},
) *APIResponse {
	mock := &APIResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
